import Image from 'next/image'
import Head from 'next/head';
import Footer from '../components/footer';
import Header from '../components/header';
function AboutUs() {
    return (
        <>
            <Head>
          <title>Children Homes Founders Association of Kenya</title>
          <meta name="description" content="Generated by create next app" />
          <meta charset="UTF-8"/>
          <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
          <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
          <link rel="shortcut icon" href="/assets/CHFAK1.jpg"/>
          
      </Head>
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />
            
            <Header />
              {/* HERO SECTION   */}
            <section className="about-us">
                
            </section>

            <div className="history">
                <div className="column left">
                    <h2>The Background</h2>
                    <div className="classified">
                        <p className="text">The organization was founded in November 2018 by a group of children home owners under the dedicated and able leadership of Bishop Hannah Njoroge.</p>

                            <p className="p_1"><br></br>These Children home owners met for several weeks looking and agonizing on the problems that children homes owners go through, day in day out, as they take care of the children.</p>
                            <p className="p_2"><br></br>They eventually came up with the idea of forming a strong organization as a support group to share their challenges, voice their grievances and to work together for the common goal of the welfare of the children homes founders for
                                the best interest if the children.</p>
                            <p><br></br>Thus, Children Home Founders Association of Kenya was born and subsequently registered as a society.</p>

                        
                    </div>

                </div>
                <div className="column right">
                    
                            <Image src="/assets/DSC_0308.jpg" width={640} height={420} alt="" />
                        </div>
                        
            </div>

            <section className="container-statements ">
                <div className="container-state_content grid">
                    <div className="card">
                        <h4 className="text">MISSION STATEMENT</h4>
                        <p>To unite Charitable Children Institutions (CCI’s) founders to speak in one voice and work in harmony with all stakeholders to promote the welfare of both the children and vulnerable groups.
                        </p>
                    </div>
                    <div className="card">
                        <h4 className="text">VISION STATEMENT</h4>
                        <p>To speak in one voice for the best interest of the children and vulnerable groups, advocating and lobbying for their rights.
                        </p>
                    </div>
                    <div className="card">
                        <h4 className="text">CORE VALUES</h4>
                        <div className="listed">
                            <div className="list">
                                <input type="radio13" id="radio13" />
                                <span className="text1">Integrity</span>
                            </div>
                            <div className="list">
                                <input type="radio14" id="radio14" />
                                <span className="text1">Accountability</span>
                            </div>
                            <div className="list">
                                <input type="radio15" id="radio15" />
                                <span className="text1">Diversity & Inclusion </span>
                            </div>
                            <div className="list">
                                <input type="radio16" id="radio16" />
                                <span className="text1">Teamwork</span>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* <!-- BOARD MEMBERS --> */}
            <section className="board-members" id="board-members">
                <div className="title">
                    <h2>THE CHFAK SECRETARIAT</h2>

                </div>
                <div className="board-content">
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image src="/assets/leadership/c.jpeg" layout='fill' alt="" />
                            </div>
                            <h3>REV. HANNAH WAIRIMU</h3>
                            <h5>CHAIRPERSON</h5>

                        </div>
                    </div>


                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image src="/assets/leadership/vc.jpeg" layout='fill' alt="" />
                            </div>
                            <h3>MR. MARTIN KOIGU</h3>
                            <h5>VICE CHAIRPERSON</h5>

                        </div>
                    </div>


                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image src="/assets/leadership/sec.jpeg" layout='fill' alt="" />
                            </div>
                            <h3>MRS. MARY MUIRURI</h3>
                            <h5>SECRETARY</h5>

                        </div>
                    </div>


                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image src="/assets/leadership/tr.jpeg" layout='fill' alt="" />
                            </div>
                            <h3>MRS. GRACE MBITHI</h3>
                            <h5>TREASURER</h5>

                        </div>
                    </div>


                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image src="/assets/leadership/cor.jpeg" layout='fill' alt="" />
                            </div>
                            <h3>MR. PAUL KARANJA</h3>
                            <h5>CO-ORDINATOR</h5>

                        </div>
                    </div>

                    
                </div>
                

            </section>
            <Footer />
        </>
    );
}

export default AboutUs