import Image from 'next/image'
import Head from 'next/head';
import Footer from '../components/footer';
import Header from '../components/header';
 function Gallerys() {
    return (
        <>
        <Head>
          <title>Children Homes Founders Association of Kenya</title>
          <meta name="description" content="Generated by create next app" />
          <meta charset="UTF-8"/>
          <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
          <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
          
      </Head>
      <link rel="shortcut icon" href="/assets/CHFAK1.jpg"/>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />

        <Header/>
 

        {/* <!-- GALLERY SECTION --> */}
    <div className="main_gallery">
        <div className="main-container">
            <div className="portfolio">
                <div className="portfolio-item medium one">

                </div>
                <div className="portfolio-item large two">

                </div>
                <div className="portfolio-item medium three">

                </div>
                <div className="portfolio-item small four">

                </div>
                <div className="portfolio-item tall five">

                </div>
                <div className="portfolio-item wide six">

                </div>
            </div>
        </div>
        <div className="main-container">
            <div className="portfolio">
                <div className="portfolio-item medium seven">

                </div>
                <div className="portfolio-item large eight">

                </div>
                <div className="portfolio-item medium nine">

                </div>
                <div className="portfolio-item small ten">

                </div>
                <div className="portfolio-item tall eleven">

                </div>
                <div className="portfolio-item wide twelve">

                </div>
            </div>
        </div>
        <div className="main-container">
            <div className="portfolio">
                <div className="portfolio-item medium b">

                </div>
                <div className="portfolio-item large c">

                </div>
                <div className="portfolio-item medium d">

                </div>
                <div className="portfolio-item small e">

                </div>
                <div className="portfolio-item tall f">

                </div>
                <div className="portfolio-item wide g">

                </div>
            </div>
        </div>
        <div className="main-container">
            <div className="portfolio">
                <div className="portfolio-item medium h">

                </div>
                <div className="portfolio-item large i">

                </div>
                <div className="portfolio-item medium j">

                </div>
                <div className="portfolio-item small k">

                </div>
                <div className="portfolio-item tall l">

                </div>
                <div className="portfolio-item wide m">

                </div>
            </div>
        </div>
        <div className="main-container">
            <div className="portfolio">
                <div className="portfolio-item medium n">

                </div>
                <div className="portfolio-item large o">

                </div>
                <div className="portfolio-item medium p">

                </div>
                <div className="portfolio-item small q">

                </div>
                <div className="portfolio-item tall r">

                </div>
                <div className="portfolio-item wide s">

                </div>
            </div>
        </div>
        <div className="main-container">
            <div className="portfolio">
                <div className="portfolio-item medium t">

                </div>
                <div className="portfolio-item large u">

                </div>
                <div className="portfolio-item medium v">

                </div>
                <div className="portfolio-item small w">

                </div>
                <div className="portfolio-item tall x">

                </div>
                <div className="portfolio-item wide y">

                </div>
            </div>
        </div>
        <div className="main-container">
            <div className="portfolio">
                <div className="portfolio-item medium a1"></div>
                <div className="portfolio-item large b1"></div>
                <div className="portfolio-item medium c1"></div>
                <div className="portfolio-item small d1"></div>
                <div className="portfolio-item tall e1"></div>
                <div className="portfolio-item wide f1"></div>
            </div>
        </div>
        <div className="main-container">
            <div className="portfolio">
                <div className="portfolio-item medium g1"></div>
                <div className="portfolio-item large h1"></div>
                <div className="portfolio-item medium i1"></div>
                <div className="portfolio-item small j1"></div>
                <div className="portfolio-item tall k1"></div>
                <div className="portfolio-item wide l1"></div>
            </div>
        </div>
        <div className="main-container">
            <div className="portfolio">
                <div className="portfolio-item medium m1"></div>
                <div className="portfolio-item large n1"></div>
                <div className="portfolio-item medium o1"></div>
                <div className="portfolio-item small p1"></div>
                <div className="portfolio-item tall q1"></div>
                <div className="portfolio-item wide r1"></div>
            </div>
        </div>
        <div className="main-container">
            <div className="portfolio">
                <div className="portfolio-item medium s1"></div>
                <div className="portfolio-item large t1"></div>
                <div className="portfolio-item medium u1"></div>
                <div className="portfolio-item small v1"></div>
                <div className="portfolio-item tall w1"></div>
                <div className="portfolio-item wide x1"></div>
            </div>
        </div>
    </div>
   
    <Footer/>
                </>
    );
  }
  
  export default Gallerys