import Image from 'next/image'
import Head from 'next/head';
import Footer from '../components/footer';
import Header from '../components/header';

function Members() {
    return (
        <>

        <Head>
            <title>Children Homes Founders Association of Kenya</title>
            <meta name="description" content="Generated by create next app" />
            <meta charset="UTF-8"/>
            <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            <link rel="shortcut icon" href="/assets/CHFAK1.jpg"/>

        </Head>
        
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />

        <Header />


        <section className="about-us">
                
        </section>


            {/* <!-- HERO SECTION --> */}
            <section className="home-members" id="home-members">
                <div className="title">
                    <h2>The Member Homes</h2>

                </div>
                <div className="home-member-content">
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/BethlehemCC.jpg" alt="" />
                            </div>
                            <h3>Bethlehem Children&rsquo;s Centre</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Soweto</p>
                            </div>
                            

                        </div>
                    </div>


                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/Bethsaida.jpg" alt="" />
                            </div>
                            <h3>Bethsaida Children&rsquo;s Home</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Mavoloni, Yala</p>
                            </div>
                            

                        </div>
                    </div>


                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/BetterLR.png" alt="" />
                            </div>
                            <h3>Better Living Rescue Centre</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Zimmerman, Kasarani</p>
                            </div>

                            {/* <!-- <p>Better Living Rescue Centre is located at Zimmerman, along Base road near Kwa Masai. <br>The program presently covers 102 children. 37 are housed at the centre while 75 are on the outreach program (these collect food, clothing and
                        school assistance from us while living with their relatives as guardians.)
                    </p> --> */}

                        </div>
                    </div>


                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/BlessedKC.jpg" alt="" />
                            </div>
                            <h3>Blessed Kids Rescue Home </h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Zimmerman, Kasarani</p>
                            </div>

                            
                        </div>
                    </div>


                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/EbenezarCH.jpg" alt="" />
                            </div>
                            <h3>Ebenezar Children&rsquo;s Home</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Ngong</p>
                            </div>
                            

                        </div>
                    </div>

                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/GodWUH.jpg" alt="" />
                            </div>
                            <h3>God With US Centre</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Githurai</p>
                            </div>
                            

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/Keumbu.jpg" alt="" />
                            </div>
                            <h3>Keumbu Holiness Children&rsquo;s Centre</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Kisii</p>
                            </div>
                            

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/Kibera.jpg" alt="" />
                            </div>
                            <h3>Kibera Pride Initiative</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Kibera</p>
                            </div>
                            {/* <!-- <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus facere eligendi laudantium cumque vero. Eaque facilis quae iste voluptas nemo.</p> --> */}

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/Manasseh.jpg" alt="" />
                            </div>
                            <h3>Manasseh Children Centre</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Ngong</p>
                            </div>
                            

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/mogra home logo.jpg" alt="" />
                            </div>
                            <h3>Mogra Children Rescue Centre</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Muthaiga North</p>
                            </div>
                            

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/Mwamko.jpg" alt="" />
                            </div>
                            <h3>Mwamko Children Centre</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Kawaha West</p>
                            </div>
                            {/* <!-- <p>Mwamko children's Centre is a charitable Christian-based Centre which was founded with an aim of caring for needy children. We currently have 40 children who include orphans, partial orphans and the vulnerable. We are located in Kahawa
                        West, Nairobi county.</p> --> */}

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/Nazareen.jpg" alt="" />
                            </div>
                            <h3>Nazareen Children&rsquo;s Home</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Kayole</p>
                            </div>
                            

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/Nema.jpg" alt="" />
                            </div>
                            <h3>Neema Children Centre</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Ruai, Kasarani</p>
                            </div>
                            

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/rimmon.png" alt="" />
                            </div>
                            <h3>Rimmon Children&rsquo;s Home</h3>
                            {/* 
                    <!-- <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus facere eligendi laudantium cumque vero. Eaque facilis quae iste voluptas nemo.</p> --> */}

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/shadow.jpg" alt="" />
                            </div>
                            <h3>Shadow Mountain Children&rsquo;s Home</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Kariobangi</p>
                            </div>
                            

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/Shelter.jpg" alt="" />
                            </div>
                            <h3>Shelter Children&rsquo;s Home</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Ngong</p>
                            </div>
                            

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/SonsManaseh.jpg" alt="" />
                            </div>
                            <h3>Sons os Manaseh Children&rsquo;s Home</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Kiserian</p>
                            </div>
                            {/* <!-- <p>Son of Manaseh Children’s Home was started in the year 2007 in Ndunyu, Dagorreti. We have 65 children under our care. They are in primary school, secondary schools and in universities, colleges and vocational training. We are located
                        in Kiserian, Isinya Pipeline Road, Kajiado County. </p> --> */}

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/watoya.jpg" alt="" />
                            </div>
                            <h3>Watoya Children Rescue Centre</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Bungoma</p>
                            </div>
                            

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/springs.jpg" alt="" />
                            </div>
                            <h3>Springs of Life Children&rsquo;s Restoration Centre</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Kibra</p>
                            </div>
                            {/* <!-- <p>The Springs of Life Children’s Restoration Center (SOLCRC) was founded at Kibra, Nairobi County in the year 2000. Currently we have 32 kids in primary school, 28 in different high schools across the country. Another lot is in college,
                        each pursuing what they are passionate about.</p> --> */}

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/st.pauls.jpg" alt="" />
                            </div>
                            <h3>St. Paul&rsquo;s Children Care Centre</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Ngong</p>
                            </div>
                            {/* <!-- <p>St. Paul’s Children Care Centre is located at Bulbul in Ngong. It was started in 1983. Over 2000 children have been transformed to be responsible, self-reliant and visionary members in the society.<br> Currently, the home hosts 34
                        children.
                    </p> --> */}

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/Tree house.jpg" alt="" />
                            </div>
                            <h3>Tree House Children&rsquo;s Home</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Lucky Summer</p>
                            </div>
                            

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/shiku.jpg" alt="" />
                            </div>
                            <h3>Bethsaida Children&rsquo;s Home</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Githurai 44</p>
                            </div>
                            

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/HEART.png" alt="" />
                            </div>
                            <h3>Heart of Care Foundation</h3>
                            <div className="loc">
                                <h4>Location:</h4>
                                <p>Githurai</p>
                            </div>
                            

                        </div>
                    </div>
                    <div className="card">
                        <div className="box">
                            <div className="imgbox">
                                <Image layout='fill' src="/assets/home-logos/victors.jpg" alt="" />
                            </div>
                            <h3>Victors Initiative Children Home</h3>

                            

                        </div>
                    </div>

                </div>
                {/* <!-- <a href="board-members.html" class="btn">BOARD MEMBERS</a> --> */}

                    {/* MORE HOMES  */}
                {/* <button class="open-button">All Member Homes</button> */}
                <div className="title">
                    <h2>All Member Homes</h2>
                </div>
                <div className="home-wrapper">
                    <div className="left-11">
                        {/* FRONT */}
                        {/* <div class="front">
                                <div class="section-wrapper">
                                    <h1>All Member Homes</h1>
                                    <div class="arranged">
                                        <h5>Amazing Wonders Rescue Centre</h5>
                                        <h6>Githurai 44, Kasarani</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Bethsaida Children’s Home</h5>
                                        <h6>Mavoloni Yata</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Better Living Rescue Centre</h5>
                                        <h6>Zimmerman, Kasarani</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Bridge of Hope Children’s Home</h5>
                                        <h6>Nakuru, Gilgil</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Great Hope Children’s Home</h5>
                                        <h6>Zimmerman, Kasarani</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Jopasha Children’s Home</h5>
                                        <h6>Githurai 44, Kasarani</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Manasse Children’s Home</h5>
                                        <h6>Zimmerman, Kasarani</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Mathew 25 Children’s Home</h5>
                                        <h6>Ngomongo, Kasarani</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Mogra Rescue Centre</h5>
                                        <h6>Muthaiga North</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Mwamko Rescue Centre</h5>
                                        <h6>Kahawa West, Kasarani</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Neema Mercy Children’s Home</h5>
                                        <h6>Ruai, Kasarani</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Rimon Children’s Home</h5>
                                        <h6>Meru</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Sarepta Children’s Home</h5>
                                        <h6>Zimmerman,Kasarani</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Shilo Children’s Home</h5>
                                        <h6>Kahawa West,Kasarani</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Springs Of Life Children’s Home</h5>
                                        <h6>Kibera,Kibra</h6>
                                    </div>
                                    <div class="arranged">
                                        <h5>Victor Initiative</h5>
                                        <h6>Km Kasarani</h6>
                                    </div>
                                    
                                </div>

                            </div> */}
                        {/* BACK */}
                        <div className="back">
                            <div className="card">
                            {/* <h1>Left</h1> */}
                            <div className="arranged">
                                <h4>Amazing Wonders Rescue Centre</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Githurai 44, Kasarani</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Bethsaida Children’s Home</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Mavoloni Yata</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Better Living Rescue Centre</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Zimmerman, Kasarani</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Bridge of Hope Children’s Home</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Nakuru, Gilgil</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Great Hope Children’s Home</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Zimmerman, Kasarani</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Jopasha Children’s Home</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Githurai 44, Kasarani</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Manasse Children’s Home</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Zimmerman, Kasarani</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Mathew 25 Children’s Home</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Ngomongo, Kasarani</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Mogra Rescue Centre</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Muthaiga North</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Mwamko Rescue Centre</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Kahawa West, Kasarani</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Neema Mercy Children’s Home</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Ruai, Kasarani</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Rimon Children’s Home</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Meru</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Sarepta Children’s Home</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Zimmerman,Kasarani</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Shilo Children’s Home</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Kahawa West,Kasarani</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Springs Of Life Children’s Home</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Kibera,Kibra</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Victor Initiative</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Km Kasarani</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Keumbu Rehema</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Kisii</p>
                                </div>
                            </div>
                            <div className="arranged">
                                <h4>Faithful Children’s Home</h4>
                                <div className="data">
                                <h5>Location:</h5>
                                <p>Kisii</p>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                    {/* MIDDLE */}
                    <div className="middle-11">
                    <div className="card">
                        {/* <h1>middle</h1> */}
                        <div className="arranged">
                        <h4>Serah’s Vision Foundation</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Umoja</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Compassionate Hand For Disabled</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Umoja</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Christ The Hope Rehabilitation</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kayole</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Arise and Shine</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Juja</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Serah’s Vision Foundation</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Umoja</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Huruma Children’s Home</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Ngong</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Shelter Childrens Home</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Ngong</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>St Paul Childrens Home Ole Kasasi</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Ngong</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Nazareen Children’s Home</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kayole</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Faith Rescue Children Centre</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Githurai</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Manase Children’s Home</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Ngong</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Ebenezer Children’s Home</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Ngong</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Heart Of Care Foundation</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Githurai</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Spirit Of Mercy</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kahawa West</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Bethsaida</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Githurai 44</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Tree House Children Family</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Lucky Summer</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Watoya Comm Hope Rescue Centre</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Bungoma</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Keumbu Holiness Children Home</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kisii</p>
                        </div>
                        </div>
                    </div>
                    </div>
                    {/* right */}
                    <div className="right-11">
                    <div className="card">
                        <div className="arranged">
                        <h4>Voice Of Hope Rescue Centre</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Njiru,Kasarani</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Christ Chapel Childrens Home</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Mathare,Kiamaiko</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Fountain Of Life Children’s Home</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Mowlem,Saika</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Soul Mercy</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Umoja Three</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Shadow Mountains</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kariobangi</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Emmanuel New Hope Rescue Centre</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kayole</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Smile Community Centre</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kayole</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Mums Love Children’s Home</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kayole</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Flomina Children’s Home</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kayole</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Rehema Daycare &amp; Orphans Centre</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kariobangi</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Good Samaritan Children’s Home</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Mathare</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>God With Us</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Githurai</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Bethlehem</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Soweto</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Victoria Joy Children Home</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kahawa West</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Bethlehem</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kirinyaga</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Vine Yard Children’s Home</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kayole</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>Kibera Pride Initiative</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Kibera</p>
                        </div>
                        </div>
                        <div className="arranged">
                        <h4>St Pauls Embulmbul</h4>
                        <div className="data">
                            <h5>Location:</h5>
                            <p>Embubul</p>
                        </div>
                        </div>
                    </div>
                    </div>
                    {/* <button class="close-button">X</button> */}
                </div>

            </section>     
            
            <Footer />
        </>
    );
}

export default Members